### PR TITLE
Parametrise target

### PR DESCRIPTION
**Pull request by ross-mcnairn-dev**
In certain runtimes (AWS Lambda in my case), we are quite restricted on where we can write files. When we extract the compressed binaries and write them to the filesystem, they need to be written under `/tmp` in Lambda, as that's the only writeable filesystem.

So, here I'm parametrising the target path.

### CODE REVIEW

**Comment by ross-mcnairn-dev** [comment]
Sorrry I did something dumb - I opened up the original PR against main so now this is stacked on main w/ the changes from the other PR - I'll set this PR to draft for now. If the other ARM PR looks good then i'll update the base after merging it and then this will be ready for review.

**Comment by JSv4** [comment]
@ross-mcnairn-dev, merged your ARM branch. Thanks for that and sorry for the delay.

**Comment by ross-mcnairn-dev** [comment]
> @ross-mcnairn-dev, merged your ARM branch. Thanks for that and sorry for the delay.

Hey, no worries at all! Happy to be able to make a small contribution here :). I'll clean this one up and open it tonight.

**Comment by ross-mcnairn-dev** [comment]
OK, @JSv4 no rush on this, but this is ready for review when you've got a few this week

**Comment by ross-mcnairn-dev** [comment]
Hey @JSv4 , do you think you'd have time to review this this week?

**Review by JSv4 — COMMENTED** [review]
Nice! Thanks for adding

**Comment by JSv4** [comment]
Thanks for the reminder @ross-mcnairn-dev

**Comment by rishabh-sagar-20** [comment]
This is great @ross-mcnairn-dev @JSv4

**Pull request merged**
