### PR TITLE
Incorporate Changes from SpotDraft Fork

### PR DESCRIPTION
**Pull request by JSv4**
Spotdraft kindly fixed a couple of typos in their fork and added MacOS support (which I can't test, sadly).

### CODE REVIEW

**Comment by rishabh-sagar-20** [comment]
Hi @JSv4, thanks for merging this. I originally planned to raise a PR once I tested the MacOS support. Also, it would be great if you could publish this on pypi.org. :)

**Comment by JSv4** [comment]
No problem @rishabh-sagar-20. Figured maybe you got busy :-). I am going to publish today. I had to tweak the packaging to get it to successfully publish. Will try again today.

**Comment by rishabh-sagar-20** [comment]
Yes @JSv4, I'm not that busy :). Anyway, please merge the other pull request(https://github.com/JSv4/Python-Redlines/pull/7) that I have submitted. This pull request is necessary because the binary extraction flow broke with this one. I have tested the MacOS support and it's working perfectly fine.

**Comment by JSv4** [comment]
Thanks. I was actually working on a similar set of changes (not finished) in PR #6. I'll merge your changes in first, then I have some packaging improvements I think are necessary for the PyPi publication to work properly.

**Comment by rishabh-sagar-20** [comment]
Thanks @JSv4

**Pull request merged**
